version: "3"

services:

  cloud-docs-server:
    image: ramesesinc/cloud-docs-server:1.0.0
    container_name: cloud-docs-server
    restart: always
    logging: 
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"
    ports: 
      - "4000:4000"
    volumes:
      - ../waterworks2/docs:/apps/server/docs/waterworks:ro