version: "3"

services:

  download-server:
    image: ramesesinc/node-download-server:0.0.2
    container_name: node-download-server
    restart: always
    logging:
      driver: "json-file"
      options: 
        max-file: "5"
        max-size: 10m
    environment:
      TZ: "Asia/Manila"
    env_file:
      - ../_res/env.conf
      - ../_custom/env.conf
    ports:
      - "8001:8000"
    volumes:
      #jessie's defaults
      - ./resources:/apps/server/public/resources
      - ../_res/env.conf:/apps/server/public/resources/res.conf
      - ../_custom/env.conf:/apps/server/public/resources/custom.conf
      #attached plugins
      - ../_custom/client:/apps/server/public/resources/downloads/modules/custom
      - ../entity/client:/apps/server/public/resources/downloads/modules/entity
      - ../waterworks2/client:/apps/server/public/resources/downloads/modules/waterworks
