version: "3"

services:

  download-server:
    image: ramesesinc/node-download-server:0.0.1
    container_name: node-download-server
    restart: always
    logging:
      driver: "json-file"
      options: 
        max-file: "5"
        max-size: 10m

    environment:
      TZ: "Asia/Manila"

    ports:
      - "8000:8000"

    volumes:
      #jessie's defaults
      - ../_custom/env.conf:/apps/server/public/resources/env.conf
      - ./resources:/apps/server/public/resources
      #attached plugins
      - ../_custom/client:/apps/server/public/resources/downloads/modules/custom
      - ../entity/client:/apps/server/public/resources/downloads/modules/entity
      - ../waterworks2/client:/apps/server/public/resources/downloads/modules/waterworks
