version: "3"

services:

  local-waterworks-server:
    image: ramesesinc/local-waterworks-server:255.01.003.001
    container_name: local-waterworks-server
    restart: always
    logging: 
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"
    env_file:
      - ./env.conf
      - ../_custom/env.conf
    ports: 
      - "8076:8070"
    volumes:
      - ../_res/connections:/apps/enterprise/connections/ext
      - ./waterworksds:/services/datasources/mainds
