version: "3"

services:

  waterworks-server:
    container_name: waterworks-server
    image: ramesesinc/local-waterworks-server:255.01.004.002
    restart: always
    logging: 
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"
    env_file:
      - ../../_res/env.conf
      - ../../_custom/env.conf
    ports: 
      - "8076:8070"
    volumes:
      - ../../_res/connections:/apps/server/services/apps/enterprise/connections/ext
      - ../../_custom/datasources/waterworksds:/apps/server/services/datasources/mainds

      - ./server/rameses-gov-etracs-waterworks2-report-services.jar:/apps/server/services/apps/enterprise/modules/rameses-gov-etracs-waterworks2-report-services.jar      
      - ./server/rameses-gov-etracs-waterworks2-services.jar:/apps/server/services/apps/enterprise/modules/rameses-gov-etracs-waterworks2-services.jar
      - ./server/rameses-enterprise-services.jar:/apps/server/services/modules/rameses-enterprise-services.jar
