version: "3"

services:

  waterworks-server:
    container_name: waterworks-server
    image: ramesesinc/local-waterworks-server:255.03.001.001
    restart: always
    logging: 
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"
    env_file:
      - ../../_res/env.conf
      - ../../_custom/env.conf
    ports: 
      - "8076:8070"
    volumes:
      - ../../_res/connections:/apps/enterprise/connections/ext
      - ../../_custom/datasources/waterworksds:/services/datasources/mainds

      - ./server/rameses-enterprise-services.jar:/services/modules/rameses-enterprise-services.jar
      - ./server/rameses-gov-etracs-waterworks2-services.jar:/apps/enterprise/modules/rameses-gov-etracs-waterworks2-services.jar
      - ./server/rameses-gov-etracs-waterworks2-report-services.jar:/apps/enterprise/modules/rameses-gov-etracs-waterworks2-report-services.jar
