version: "3"
services:
  migration-redis:
    image: redis:5.0.6
    container_name: migration-redis
    restart: always
    logging: 
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"
    volumes:
      - ../_custom/data/dbmigration-redis:/data
    expose: 
      - 6379
    ports:
      - "6379:6379"

  migration-server:
    image: ramesesinc/db-migration-server:0.0.1
    container_name: db-migration-server
    restart: always
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: 10m
    depends_on:
      - migration-redis        
    links:
      - migration-redis
    environment:
      TZ: "Asia/Manila"
    ports:
      - "5000:5000"
    volumes:
      - ../waterworks2/migrations:/dbm-root/waterworks
    