version: "3"

services:
  
  download-server:
    image: nginx:latest
    container_name: download-server
    restart: always
    logging:
      driver: "json-file"
      options: 
        max-file: "5"
        max-size: 10m
    environment:
      TZ: "Asia/Manila"
    env_file:
      - ../_custom/env.conf
    ports:
      - "81:80"
      - "8000:80"
    volumes:
      - ../download/_src:/_src
      - ../download/_src/conf.d:/etc/nginx/conf.d
      - ../download/_src/nginx.conf:/etc/nginx/nginx.conf
      - ../download/resources:/resources
      - ../entity/client:/resources/downloads/modules/entity
    command: ["sh", "/_src/scripts/run.sh" ]


  etracs25-server:
    image: ramesesinc/etracs25-server-city:255.02.007
    container_name: etracs25-server
    restart: always
    logging:
      driver: "json-file"
      options: 
        max-file: "5"
        max-size: 10m
    env_file:
      - ./env.conf
      - ../_custom/env.conf
    ports:
      - "8060:8060"
      - "8061:8061"
      - "8070:8070"
      - "8080:8080"
    volumes:
      - ../_res/connections:/apps/etracs25/connections/ext
      - ./modules:/apps/etracs25/modules

      - ./dev_modules/rameses-treasury-common-services.jar:/services/modules/rameses-treasury-common-services.jar

      - ./dev_modules/gov:/gov
      - ./dev_modules/gov/etracs__gov.conf:/apps/etracs25/modules.conf.d/etracs__gov.conf

      - ./dev_modules/rptis:/rptis
      - ./dev_modules/rptis/etracs_rptis.conf:/apps/etracs25/modules.conf.d/etracs_rptis.conf
